# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request, workflow_dispatch]

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn      
        
      - name: Build
        run: yarn build

  Test:
    name: Test
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn  

      - name: Test
        run: yarn test --watchAll=false

  Linter:
    name: Linter
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn  

      - name: Run linter
        run: yarn run eslint src
