# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn      
        
      - name: Build
        run: yarn build

      - name: Run linter
        run: eslint src
        
      - name: Test
        run: yarn test --watchAll=false

  Test:
    name: Test
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: yarn test --watchAll=false

  Linter:
    name: Linter
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2

      - name: Run linter
        run: eslint src